export enum BackendEndpoints {
     GET_USER = 'auth/authorization/user',
     GET_USERS = 'auth/user',
     LOGIN = 'auth/authorization/login',
     REGISTER = 'auth/authorization/registration',
     REFRESH = 'auth/token/refresh',
     LOGOUT = 'auth/token/revoke',
     GET_ANIMALS = 'hunting/animal',
     GET_HUNTINGSEASSON = 'hunting/huntingSeason',
     GET_FEEDING = 'hunting/feeding',
     GET_RANGERS = 'auth/user/ranger',
     GET_LANDS = 'hunting/land',
     GET_PRODUCTS = 'hunting/product',
     GET_RAIDS = 'hunting/raid',
     GET_PERMISSION = 'hunting/permission',
     GET_TRIP = 'hunting/trip',
     PAYMENT = 'hunting/payment',
     GET_HUNTINGLICENSE = 'auth/hunting',
     GET_TRIP_PARTICIPANT = 'hunting/TripParticipant',
     GET_PRODUCT = 'hunting/rent/product',
     GET_RENT_PRODUCT = 'hunting/rent/RentProduct',
}