export const RoutesMap = {
    home: '/',
    main: '/',
    singIn: '/login',
    singUp: '/registration',
    chat: '/chat',
    managing: '/managing',
    trip: '/trip',
    animal: '/animal',
    feeding: '/feeding',
    reporting: '/reporting',
    raid: '/raid',
    permission: '/permission',
    paymantFee: '/paymantFee',
    checkHuntingLicense: '/checkHuntingLicense',
    profile: '/profile',
    myTrips: '/profile/myTrips',
};