version: '3.8'

services:
    sqlserver: 
        ports:
          - 1433:1433
        environment:
          - ACCEPT_EULA=Y
          - MSSQL_SA_PASSWORD=Passw0rd
        restart: unless-stopped

    gateway:
        ports:
            - 5001:8080
        restart: unless-stopped
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker

    identity:
        ports:
            - 9001:8080
        restart: unless-stopped
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
        depends_on:
            - gateway
            - sqlserver