version: '3.8'

volumes:
    sqlserver_data:

services:
    sqlserver: 
        container_name: SqlServer
        image: mcr.microsoft.com/mssql/server:2022-latest
        volumes:
             - sqlserver_data:/var/opt/mssql

    gateway:
        container_name: Gateway
        build:
            context: "."
            dockerfile: /gateways/OcelotApiGateway/Dockerfile
        
    identity:
        container_name: Identity
        build:
            context: "."
            dockerfile: /services/Identity/Identity.API/Dockerfile