version: '3.8'

services:
  rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped

  sqlserver:
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw0rd
    restart: unless-stopped

  kibana:
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL:http://localhost:9200
    links:
      - elasticsearch
    networks:
      - elk
    depends_on:
      - elasticsearch

  elasticsearch:
    ports:
      - 9200:9200
    environment:
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - discovery.type=single-node
    networks:
      - elk

  gateway:
    ports:
      - 5001:8080
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

  identity:
    ports:
      - 9001:8080
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - gateway
      - sqlserver
  chat:
    ports:
      - 8001:8080
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - gateway
      - sqlserver
  redis:
    ports: 
         - 6379:6379
    environment:
        - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped

networks:
  elk:
    driver: bridge
